# Generated by Django 5.1 on 2024-09-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_objects',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
